applicantform/applicantform/Models/Shared/Message.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ModelView;
using System.Web.Mvc;

namespace applicantform.Models.Shared
{
    public class Message
    {
        public string PropertyName { get; set; }
        public string PropertyValue { get; set; }

        public static List<Message> GetMessageErrorByModel(
            string modelName, ModelStateDictionary modelData)
        {
            List<Message> listError = new List<Message>();

            List<Message> listErrorByModel = GetMessageError(modelName, modelData);

            List<string> listFieldClass = typeof(applicantModelView).GetProperties().Select(a => a.Name).ToList();

            foreach (var field in listFieldClass)
            {
                int index = listErrorByModel.FindIndex(n => n.PropertyName == field);

                Message message = new Message();
                message.PropertyName = field;

                if (index >= 0)
                {
                    message.PropertyValue = listErrorByModel[index].PropertyValue;
                }
                else { message.PropertyValue = string.Empty; }
                listError.Add(message);
            }
            return listError;
        }

        static List<Message> GetMessageError(string modelName,
            ModelStateDictionary modelData)
        {
            List<Message> listError = new List<Message>();
            foreach (KeyValuePair<string, ModelState>
                ms in modelData)
            {
                ModelState modelState = ms.Value;
                Message message = new Message();
                message.PropertyName =
                    GetFieldNameByObject(modelName + ".", ms.Key);

                if (modelState.Errors.Count > 0)
                {
                    message.PropertyValue =
                   string.Join("\n", GetErrorMessageByField(modelState));
                }
                else
                {
                    message.PropertyValue = string.Empty;
                }
                listError.Add(message);
            }
            return listError;
        }

        private static List<string> GetErrorMessageByField(
            ModelState modelState)
        {
            List<string> listError = new List<string>();
            foreach (ModelError error in modelState.Errors)
            {
                listError.Add(error.ErrorMessage);
            }

            return listError;
        }

        private static string GetFieldNameByObject(string v,
            string key)
        {
            if (key.Contains(v))
            {
                key = key.Replace(v, "");
            }
            return key;
        }
    }
}

applicantform/applicantform/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace applicantform.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

applicantform/applicantform/Controllers/applicantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ModelView;
using ModelAccess;
using applicantform.Models.Shared;

namespace applicantform.Controllers
{
    public class applicantController : Controller
    {
        // GET: applicant
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            List<applicantModelView> List = new List<applicantModelView>();
            List = applicantModelAccess.GetListAll();
            return PartialView("List", List);
        }

        public ActionResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult Create(applicantModelView paramModel)
        {
            try
            {
                paramModel.is_delete = false;

                if (ModelState.IsValid)
                {
                    return Json(new
                    {
                        success = applicantModelAccess.Insert(paramModel),
                        message = applicantModelAccess.Message
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    List<Message> listMessage =
                     Message.GetMessageErrorByModel("paramModel", ModelState);

                    return Json(new
                    {
                        success = false,
                        message = listMessage
                    }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception hasError)
            {
                return Json(new
                {
                    success = false,
                    message = hasError.Message
                }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Edit(Int32 paramId)
        {
            return PartialView(applicantModelAccess.GetDetailsById(paramId));
        }

        [HttpPost]
        public ActionResult Edit(applicantModelView paramModel)
        {
            try
            {

                return Json(new
                {
                    success = applicantModelAccess.Update(paramModel),
                    message = applicantModelAccess.Message
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception hasError)
            {
                return Json(new
                {
                    success = false,
                    message = hasError.Message
                },
                JsonRequestBehavior.AllowGet);
            }
        }


        public ActionResult Delete(Int32 IdDelete)
        {
            return PartialView(applicantModelAccess.GetDetailsById(IdDelete));
        }

        [HttpPost]
        public ActionResult Delete(applicantModelView paramModelDelete)
        {
            try
            {
                paramModelDelete.is_delete = true;

                return Json(new
                {
                    success = applicantModelAccess.Delete(paramModelDelete),
                    message = applicantModelAccess.Message
                }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception hasError)
            {
                return Json(new
                {
                    success = false,
                    message = hasError.Message
                }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

applicantform/applicantform/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

applicantform/applicantform/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

applicantform/applicantform/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

applicantform/applicantform/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("List","Index","applicant")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

applicantform/applicantform/Views/applicant/Create.cshtml
@model ModelView.applicantModelView

<div class="panel-group">
    <div class="panel panel-default">
        <div class="form-group col-sm-6">
            <label for="nama" style="color: #023692">Nama *</label><br />
            <input class="form-control" type="text" id="nama" name="nama" style="border-color: #023692; height: 1cm">
                @Html.ValidationMessageFor(model => model.nama, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-sm-6">
            <label for="nomor_hp" style="color: #023692">Nomor Handphone *</label><br />
            <input class="form-control" type="text" id="nomor_hp" name="nomor_hp" style="border-color: #023692; height: 1cm">
                @Html.ValidationMessageFor(model => model.nomor_hp, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-sm-6">
            <label for="email" style="color: #023692">E-mail</label><br />
            <input class="form-control" type="text" id="email" name="email" style="border-color: #023692; height: 1cm">
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-sm-6">
            <label for="tgl_lahir" style="color: #023692">Tanggal Lahir *</label><br />
            <input class="form-control" type="date" id="tgl_lahir" name="tgl_lahir" style="border-color: #023692; height: 1cm">
                @Html.ValidationMessageFor(model => model.tgl_lahir, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-sm-6">
            <label for="alamat" style="color: #023692">Alamat *</label><br />
            <input class="form-control" type="text" id="alamat" name="alamat" style="border-color: #023692; height: 1cm">
                @Html.ValidationMessageFor(model => model.alamat, "", new { @class = "text-danger" })
        </div>

        @*<input class="form-control" type="radio" id="jurusan" name="jurusan" style="border-color: #023692; height: 1cm">
        <label for="it">IT</label><br>
        <input class="form-control" type="radio" id="jurusan" name="jurusan" style="border-color: #023692; height: 1cm">
        <label for="nonit">Non IT</label><br>*@
        <div class="form-group col-sm-6">
            <label for="jurusan" style="color: #023692">Jurusan Kuliah yang dibidangi ?</label><br>
            @Html.DropDownList("jurusan", new List<SelectListItem>{
        new SelectListItem{ Text="--Jurusan--", Value="", Selected=true},
        new SelectListItem{ Text="IT", Value="IT"},
        new SelectListItem{ Text="NON IT", Value="NON_IT"}
        }, new { @class = "form-control", style = "border-color: #023692; height: 1cm" })
            @Html.ValidationMessageFor(model => model.jurusan, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-sm-6">
            <label for="pertanyaan" style="color: #023692">Pertanyaan ?</label><br />
            <textarea class="form-control" rows="5" id="pertanyaan" name="pertanyaan" style="border-color: #023692; height: 2cm"></textarea>
                @Html.ValidationMessageFor(model => model.pertanyaan, "", new { @class = "text-danger" })
        </div>

        <div class="btn-group col-md-offset-10" role="group" aria-label="Basic example">
            <button type="button" class="btn btn-save btn-primary" id="btn_create_save">Kirim</button>
            <input type="button" value="Cancel" title="Cancel" class="btn btn-danger" data-dismiss="modal" />
        </div>
    </div>
</div>

applicantform/applicantform/Views/applicant/Delete.cshtml
@model ModelView.applicantModelView

<div class="modal-body" style="color: #c81912">
    <div class="row">
        <div class="col-md-3"><i class="fas fa-trash" style="display:block; width: 70%; height: 70%; margin: auto"></i></div>
        <div class="col-md-9">
            <h3 style="margin: auto; padding: 10px">Anda yakin ingin menghapus <br />@Html.DisplayFor(model => model.nama)?</h3>
            @Html.HiddenFor(model => Model.id)
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-batal btn-secondary" id="batal" onclick="batalAction(this)">Tidak</button>
    <button type="button" class="btn btn-primary btnKonfirmasiDelete" id="btn_delete" style="background-color:#c81912">Ya</button>
</div>

<script>
    batalAction=(e)=>{
        $("#modalDelete").modal('hide');
    }
</script>

applicantform/applicantform/Views/applicant/Edit.cshtml
@model ModelView.applicantModelView

@Html.AntiForgeryToken()
<div class="form-horizontal">
    <div class="row">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)
        <div class="form-group col-sm-6">
            <label for="nama" style="color: #023692">Nama *</label>
            <input class="form-control" type="text" id="nama" name="nama" style="border-color: #023692; height: 1cm" value="@Model.nama">
            <div class="col-md-10">
                @Html.ValidationMessageFor(model => model.nama, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-sm-6">
            <label for="nomor_hp" style="color: #023692">Nomor Handphone *</label>
            <input class="form-control" type="text" id="nomor_hp" name="nomor_hp" style="border-color: #023692; height: 1cm" value="@Model.nomor_hp">
            <div class="col-md-10">
                @Html.ValidationMessageFor(model => model.nomor_hp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-sm-6">
            <label for="email" style="color: #023692">E-mail</label>
            <input class="form-control" type="text" id="email" name="email" style="border-color: #023692; height: 1cm" value="@Model.email">
            <div class="col-md-10">
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-sm-6">
            <label for="tgl_lahir" style="color: #023692">Tanggal Lahir *</label>
            <input class="form-control" type="date" id="tgl_lahir" name="tgl_lahir" style="border-color: #023692; height: 1cm" value="@Model.tgl_lahir">
            <div class="col-md-10">
                @Html.ValidationMessageFor(model => model.tgl_lahir, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-sm-6">
            <label for="alamat" style="color: #023692">Alamat *</label>
            <input class="form-control" type="text" id="alamat" name="alamat" style="border-color: #023692; height: 1cm" value="@Model.alamat">
            <div class="col-md-10">
                @Html.ValidationMessageFor(model => model.alamat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-sm-6">
            <label for="jurusan" style="color: #023692">Jurusan Kuliah yang Dibidangi ?</label><br>
            @Html.DropDownList("jurusan", new List<SelectListItem>{
        new SelectListItem{ Text="--Jurusan--", Value="", Selected=true},
        new SelectListItem{ Text="IT", Value="IT"},
        new SelectListItem{ Text="NON IT", Value="NON_IT"}
        }, new { @class = "form-control", style = "border-color: #023692; height: 1cm" })
            @Html.ValidationMessageFor(model => model.jurusan, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-sm-10">
            <label for="pertanyaan" style="color: #023692">Pertanyaan ?</label>
            <input class="form-control" rows="5" id="pertanyaan" name="pertanyaan" style="border-color: #023692; height: 2cm" value="@Model.pertanyaan">
            @Html.ValidationMessageFor(model => model.pertanyaan, "", new { @class = "text-danger" })
        </div>

        <div class="btn-group col-md-offset-10" role="group" aria-label="Basic example">
            <input type="button" value="Edit" title="Edit" class="btn btn-primary" id="Edit" />
            <input type="button" value="Cancel" title="Cancel" class="btn btn-danger" data-dismiss="modal" />
        </div>
    </div>
</div>

applicantform/applicantform/Views/applicant/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="header">
                <h1>List Applicant</h1>
            </div>
            &nbsp;
            <button class="btn btn-info" title="Tambah Data" id="btn_create" name="btn_create">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            </button>
        </div>
        <div class="panel-body">
            <div id="table-list" name="table-list">
                @Html.Partial("List")
            </div>
        </div>
    </div>
</div>

<!-- Model Content -->
<div class="modal fade" id="modal-edit-form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabelAdd" aria-hidden="true">
    <div class="modal-dialog" role="document" style="width:900px">
        <!-- Modal Content-->
        <div class="modal-content">
            <div class="modal-header">
                <!--<button class="close" data-dismiss="modal">&times;</button>-->
                <h3 class="modal-title modal-mn"></h3>
            </div>
            <div class="modal-bind-content" style="margin-top:10px; margin-left:40px; margin-right:40px; margin-bottom:10px">
                <div class="modal-body">
                    <input type="hidden" id="action" value="">
                </div>
            </div>
        </div>
    </div>
</div>

<!--Modal Popup Delete-->
<div class="modal fade" id="modalDelete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document" style="width: 500px">
        <div class="modal-content">
            <div class="modal-header" style="background: #B61111">
                <h3 class="modal-title modal-mn"></h3>
            </div>
            <div class="modal-bind-content" style="margin-top:10px; margin-left:40px; margin-right:40px; margin-bottom:10px">
                <div class="modal-body">

                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
    var vjs_loading = '<div class="progress progress-striped active" style="margin-bottom:0"><div class="progress-bar" style="width:100%"></div></div>';

    $(document).ready(function () {
        ShowList()
    });

    //Method untuk Menampilkan Data
    function ShowList() {
        debugger;
        $("#table-list").html(vjs_loading);

        $.ajax({
            url: '@Url.Action("List", "applicant")',
            type: 'get',
            data: {
            },
            success: function (result) {
                $("#table-list").html(result);
            }
        });
    }

        $("#btn_create").click(function () {
            /* setting konfigurasi pop-up / modal */
            $("#modal-edit-form").modal("show"); //memunculkan pop-up
            $(".modal-title").html("Tambah Data"); //memunculkan title pop-up
            $(".modal-bind-content").html(vjs_loading); //mensetting body menjadi animasi loading

            /* Setting body modal dari view */
            $.ajax({
                url: '@Url.Action("Create","applicant")',
                type: 'get',
                success: function (result) {
                    $(".modal-bind-content").html(result);
                }
            });
        });

    $(document).on("click", "#btn_create_save", function () {
        debugger;
        //Ambil Nilai Pada Form
        var vjs_name = $("#nama").val();
        var vjs_nomor_hp = $("#nomor_hp").val();
        var vjs_email = $("#email").val();
        var vjs_tglLahir = $("#tgl_lahir").val();
        var vjs_alamat = $("#alamat").val();
        var vjs_jurusan = $("#jurusan").val();
        var vjs_pertanyaan = $("#pertanyaan").val();

        //Membuat Variabel Json / class dari nilai form
        var item = {
            nama: vjs_name,
            nomor_hp: vjs_nomor_hp,
            email: vjs_email,
            tgl_lahir: vjs_tglLahir,
            alamat: vjs_alamat,
            jurusan: vjs_jurusan,
            pertanyaan: vjs_pertanyaan,
        };

        $.ajax({
            url: '@Url.Action("Create", "applicant")',
            type: 'post',
            data: { paramModel: item },
            success: function (result) {
                if (result.success) {
                    alert("Data Berhasil Dikirim");
                    $("#modal-edit-form").modal("hide"); //menutup pop-up
                    ShowList();
                }
                else {
                    alert(result.message);
                }
            }
        });
    });

    //Popup Edit
    $(document).on("click", ".btn_grid_edit", function () {
        $("#modal-edit-form").modal("show");
        $(".modal-title").html("Update Applicant");
        $(".modal-bind-content").html(vjs_loading);

        //Membuat variabel tombol edit grid
        var vjs_Id = $(this).attr("data-id");

        $.ajax({
            url: '@Url.Action("Edit","applicant")',
            type: 'get',
            data: { paramId: vjs_Id },
            success: function (result) {
                $(".modal-bind-content").html(result);
            }
        });
    });

    $(document).on("click", "#Edit", function () {
        debugger;
        //Ambil Nilai Pada Form
        var vjs_Id = $("#id").val();
        var vjs_name = $("#nama").val();
        var vjs_nomor_hp = $("#nomor_hp").val();
        var vjs_email = $("#email").val();
        var vjs_tglLahir = $("#tgl_lahir").val();
        var vjs_alamat = $("#alamat").val();
        var vjs_jurusan = $("#jurusan").val();
        var vjs_pertanyaan = $("#pertanyaan").val();

        //Membuat Variabel Json / class dari nilai form
        var itemEdit = {
            id: vjs_Id,
            nama: vjs_name,
            nomor_hp: vjs_nomor_hp,
            email: vjs_email,
            tgl_lahir: vjs_tglLahir,
            alamat: vjs_alamat,
            jurusan: vjs_jurusan,
            pertanyaan: vjs_pertanyaan,
            is_delete: false
        };

        $.ajax({
            url: '@Url.Action("Edit", "applicant")',
            type: 'POST',
            data: { paramModel: itemEdit },
            success: function (result) {
                if (result.success) {
                    alert("Data Berhasil Diedit");
                    $("#modal-edit-form").modal("hide"); //menutup pop-up
                    ShowList();
                }
                else {
                    alert(result.message);
                }
            }
        });
    });

    //Popup delete
    $(document).on("click", ".btn_grid_delete", function () {
        debugger;
        $("#modalDelete").modal("show");
        $(".modal-title").html("Hapus Data Applicant");
        $(".modal-bind-content").html(vjs_loading);

        //Membuat variabel tombol edit grid
        var vjs_id = $(this).attr("data-id");

        $.ajax({
            url: '@Url.Action("Delete","applicant")',
                type: 'get',
                data: { IdDelete: vjs_id },
                success: function (result) {
                    $(".modal-bind-content").html(result);
                }
            });
        });

                $(document).on("click", "#btn_delete", function () {
            var vjs_id = $("#id").val();

            var itemDelete = {
                Id: vjs_id
            }

            $.ajax({
                url: '@Url.Action("Delete", "applicant")',
                type: 'post',
                data: { paramModelDelete: itemDelete },
                success: function (result) {
                    if (result.success) {
                        alert("Data Berhasil Dihapus");
                        $("#modalDelete").modal("hide");
                        ShowList();
                    }
                    else {
                        alert(result.message);
                    }
                }
            });
        });
    </script>
<script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
}

applicantform/applicantform/Views/applicant/List.cshtml
@model IEnumerable<ModelView.applicantModelView>

<table class="table">
    <tr>
        <th>
            <font size="4" color="#023692">Nama</font>
        </th>
        <th>
            <font size="4" color="#023692">Nomor Handphone</font>
        </th>
        <th>
            <font size="4" color="#023692">Email</font>
        </th>
        <th>
            <font size="4" color="#023692">Tanggal Lahir</font>
        </th>
        <th>
            <font size="4" color="#023692">Alamat</font>
        </th>
        <th>
            <font size="4" color="#023692">Jurusan</font>
        </th>
        <th>
            <font size="4" color="#023692">Pertanyaan</font>
        </th>
        <th>
            <font size="4" color="#023692">Action</font>
        </th>
    </tr>

    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.nama)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nomor_hp)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tgl_lahir)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.alamat)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.jurusan)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.pertanyaan)
                </td>
                <td>
                    <button title="Edit" class="btn btn-warning btn_grid_edit" data-id="@item.id">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true">
                        </span>
                    </button>
                    <button title="Delete" class="btn btn-danger btn_grid_delete" data-id="@item.id">
                        <span class="glyphicon glyphicon-trash" aria-hidden="true">
                        </span>
                    </button>
                </td>
            </tr>
        }
    }

</table>